// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5GIrSI8DrGn0lJ2LWbqyJ5emMtaqBB9Y',
    appId: '1:623200839807:web:8e6a50a94b2d32ab24774a',
    messagingSenderId: '623200839807',
    projectId: 'foodecommerce-c00fa',
    authDomain: 'foodecommerce-c00fa.firebaseapp.com',
    storageBucket: 'foodecommerce-c00fa.firebasestorage.app',
    measurementId: 'G-FMN325QBFK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8AVXYUNL6hagp5mh4Pk4WsiLOnJxhAm0',
    appId: '1:623200839807:android:a7aa6da31f2a883924774a',
    messagingSenderId: '623200839807',
    projectId: 'foodecommerce-c00fa',
    storageBucket: 'foodecommerce-c00fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAir-D8wqogsLyAsVN4mg5gWZLiRFmiWEI',
    appId: '1:623200839807:ios:0d4ef021232a94f424774a',
    messagingSenderId: '623200839807',
    projectId: 'foodecommerce-c00fa',
    storageBucket: 'foodecommerce-c00fa.firebasestorage.app',
    iosBundleId: 'com.example.foodecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAir-D8wqogsLyAsVN4mg5gWZLiRFmiWEI',
    appId: '1:623200839807:ios:0d4ef021232a94f424774a',
    messagingSenderId: '623200839807',
    projectId: 'foodecommerce-c00fa',
    storageBucket: 'foodecommerce-c00fa.firebasestorage.app',
    iosBundleId: 'com.example.foodecommerce',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5GIrSI8DrGn0lJ2LWbqyJ5emMtaqBB9Y',
    appId: '1:623200839807:web:caa024aa58288f1624774a',
    messagingSenderId: '623200839807',
    projectId: 'foodecommerce-c00fa',
    authDomain: 'foodecommerce-c00fa.firebaseapp.com',
    storageBucket: 'foodecommerce-c00fa.firebasestorage.app',
    measurementId: 'G-VFHXDTKG7F',
  );

}